repos:
- repo: https://github.com/PyCQA/isort
  rev: 5.11.4
  hooks:
    - id: isort
      files: "\\.(py)$"
      args: [--settings-path=pyproject.toml]
- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.3
  hooks:
    - id: pycln
      args: [--config=pyproject.toml]
- repo: https://github.com/PyCQA/docformatter
  rev: v1.5.1
  hooks:
    - id: docformatter
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 5191f11
  hooks:
    - id: mixed-line-ending
      args: [--fix=no]
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml
    - id: name-tests-test
      args: [--pytest-test-first]
      exclude: "tests/utils.py"
    - id: no-commit-to-branch
      args: [--branch, rc, --branch, main]
    - id: pretty-format-json
      args: [--autofix]
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      files: "\\.(py)$"
      args: [--config=pyproject.toml]
    - id: black-jupyter
      files: "\\.(ipynb)$"
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      files: "\\.(py)$"
      args: [--config=.flake8]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
    - id: mypy
      args: [--config-file=pyproject.toml]
